### ISSUE TITLE
Cant compile server

### ISSUE THREAD

**Issue by JasonP01** [xpdustry/imperium#124]
### Where did the bug happen?

Mindustry

### The bug(s)

[04-19-2024 23:59:48] [I] [DistributorLoggerSimple] Initialized simple logger
[04-19-2024 23:59:55] [I] 6 mods loaded.
[04-19-2024 23:59:55] [I] [KotlinRuntime] Kotlin stdlib and reflect (v1.9.23) are now available.
[04-19-2024 23:59:55] [I] [KotlinRuntime] Kotlin coroutines (v1.7.3) are now available.
[04-19-2024 23:59:56] [I] [NoHorny] Initialized nohorny, to the horny jail we go.
[04-19-2024 23:59:56] [I] Server loaded. Type 'help' for help.
[04-19-2024 23:59:58] [E] com.sksamuel.hoplite.ConfigException: Error loading config because:

    - Could not instantiate 'com.xpdustry.imperium.common.config.ImperiumConfig' because:

        - 'server': Could not find appropriate subclass of class com.xpdustry.imperium.common.config.ServerConfig: Tried com.xpdustry.imperium.common.config.ServerConfig$Discord, com.xpdustry.imperium.common.config.ServerConfig$Mindustry, com.xpdustry.imperium.common.config.ServerConfig$None (config\mods\imperium\config.yaml:1:2)
        at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:219)
        at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:216)
        at com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:115)
        at com.sksamuel.hoplite.ConfigLoader.returnOrThrow(ConfigLoader.kt:216)
        at com.xpdustry.imperium.common.config.ImperiumConfigProvider.create(ImperiumConfigProvider.kt:69)
        at com.xpdustry.imperium.common.config.ImperiumConfigProvider.create(ImperiumConfigProvider.kt:30)
        at com.xpdustry.imperium.common.inject.SimpleMutableInstanceManager$NotifyingInstanceProvider.create(InstanceManager.kt:110)
        at com.xpdustry.imperium.common.inject.SimpleMutableInstanceManager.getOrNull(InstanceManager.kt:77)
        at com.xpdustry.imperium.common.inject.SimpleMutableInstanceManager.createAll(InstanceManager.kt:61)
        at com.xpdustry.imperium.mindustry.ImperiumPlugin.onLoad(ImperiumPlugin.kt:101)
        at com.xpdustry.distributor.plugin.AbstractMindustryPlugin$PluginApplicationListener.init(AbstractMindustryPlugin.java:148)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:64)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)

### Steps to reproduce it

idk i just compiled the shadowJar then ran then the mindus server start cmd, i didnt do docker cause shi was taking 7 years and im not waiting that long with 0 console movement to see anything happening at all, config.yaml is ctrl v (it doesnt like tab character ;-;)

This is probably my fault, ill try the client and comment on this if issues, (prob same)

### Submission

- [X] I have searched the open and closed issues to make sure this problem has not already been reported

**Comment by JasonP01** [comment]
client works fine, however i will attempt to make it more effiecent with some foos changes (multi threaded server list loading, ect)

**Comment by JasonP01** [comment]
config.yaml is correct, i already saw its error and solved it, there is no issue with the config.yaml :(

**Comment by JasonP01** [comment]
C:\Users\jason\imperium>docker-compose up -d
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Dimperium%22%3Atrue%7D%7D": open //./pipe/docker_

@phinner wot this mean (subsequent command before this was :imperium-mindustry:shadowJar)

**Comment by JasonP01** [comment]
nevermind, i forgor to start docker engine

**Comment by JasonP01** [comment]
> Task :imperium-mindustry:runMindustryServer
[04-23-2024 01:48:42] [I] [DistributorLoggerSimple] Initialized simple logger
[04-23-2024 01:49:16] [I] 6 mods loaded.
[04-23-2024 01:49:16] [I] [KotlinRuntime] Kotlin stdlib and reflect (v1.9.23) are now available.
[04-23-2024 01:49:16] [I] [KotlinRuntime] Kotlin coroutines (v1.7.3) are now available.
[04-23-2024 01:49:16] [I] [NoHorny] Initialized nohorny, to the horny jail we go.
[04-23-2024 01:49:16] [I] Server loaded. Type 'help' for help.
[04-23-2024 01:49:44] [E] com.sksamuel.hoplite.ConfigException: Error loading config because:

    - Could not instantiate 'com.xpdustry.imperium.common.config.ImperiumConfig' because:

        - 'server': Could not find appropriate subclass of class com.xpdustry.imperium.common.config.ServerConfig: Tried com.xpdustry.imperium.common.config.ServerConfig$Discord, com.xpdustry.imperium.common.config.ServerConfig$Mindustry, com.xpdustry.imperium.common.config.ServerConfig$None (config\mods\imperium\config.yaml:1:2)
        at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:219)
        at com.sksamuel.hoplite.ConfigLoader$returnOrThrow$1.invoke(ConfigLoader.kt:216)
        at com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:115)
        at com.sksamuel.hoplite.ConfigLoader.returnOrThrow(ConfigLoader.kt:216)
        at com.xpdustry.imperium.common.config.ImperiumConfigProvider.create(ImperiumConfigProvider.kt:69)
        at com.xpdustry.imperium.common.config.ImperiumConfigProvider.create(ImperiumConfigProvider.kt:30)
        at com.xpdustry.imperium.common.inject.SimpleMutableInstanceManager$NotifyingInstanceProvider.create(InstanceManager.kt:110)
        at com.xpdustry.imperium.common.inject.SimpleMutableInstanceManager.getOrNull(InstanceManager.kt:77)
        at com.xpdustry.imperium.common.inject.SimpleMutableInstanceManager.createAll(InstanceManager.kt:61)
        at com.xpdustry.imperium.mindustry.ImperiumPlugin.onLoad(ImperiumPlugin.kt:101)
        at com.xpdustry.distributor.plugin.AbstractMindustryPlugin$PluginApplicationListener.init(AbstractMindustryPlugin.java:148)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:64)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:52)
        
        
Bruh, i let docker compose run, they all completed, i only told it to compile and run the mindustry instance and its failing, at this point i dont want to try compiling this nonsense again, and the localhost had absoltuley 0 information being sent to it after it completed fully

**Comment by JasonP01** [comment]
config.yaml is the exact same as readme except name is "Testing" which i just realised is bad for my current ver

OMFG im so done with this and the stupid nonsense

**Comment by phinner** [comment]
El famoso works on my machine :sunglasses:

**Comment by JasonP01** [comment]
i want your machine, pissed at mine

however i theorize docker fixed my keyboard (no evidence) so i guess its alright

**Comment by JasonP01** [comment]
you implemented fix for my issues, plus compiled correctly so this is fine
